// Generated by ego on Sun Jun 14 13:23:31 2015.
// DO NOT EDIT

package main
import (
"fmt"
"html"
"io"
"github.com/kyokomi/slackbot/plugins"
)
//line templates/index.html.ego:1
 func IndexTmpl(w io.Writer, pList []plugins.Plugin) error  {
//line templates/index.html.ego:2
_, _ = fmt.Fprint(w, "\n\n")
//line templates/index.html.ego:4
_, _ = fmt.Fprint(w, "\n\n<!DOCTYPE html>\n<html>\n<head lang=\"en\">\n    <meta charset=\"UTF-8\">\n    <title>いーすん管理画面</title>\n</head>\n<body>\n    <h1>いーすん管理画面</h1>\n    ")
//line templates/index.html.ego:13
 for idx, p := range pList { 
//line templates/index.html.ego:14
_, _ = fmt.Fprint(w, "\n    <li>")
//line templates/index.html.ego:14
_, _ = fmt.Fprint(w, html.EscapeString(fmt.Sprintf("%v",  idx )))
//line templates/index.html.ego:14
_, _ = fmt.Fprint(w, " : ")
//line templates/index.html.ego:14
_, _ = fmt.Fprint(w, html.EscapeString(fmt.Sprintf("%v",  p.Name() )))
//line templates/index.html.ego:14
_, _ = fmt.Fprint(w, "</li>\n    ")
//line templates/index.html.ego:15
 } 
//line templates/index.html.ego:16
_, _ = fmt.Fprint(w, "\n</body>\n</html>")
return nil
}
